version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DB_HOST=145.223.21.117
      - DB_PORT=3306
      - DB_NAME=japane
      - DB_USER=debian-sys-maint
      - DB_PASSWORD=Str0ngP@ssw0rd!
      - SECRET_KEY=your-secret-key-change-this
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

